name: Terraform-GitHub-Actions
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
  AWS_PUBLIC_SSH_KEY: ${{secrets.AWS_PUBLIC_SSH_KEY}}
  AWS_PRIVATE_SSH_KEY: ${{secrets.AWS_PRIVATE_SSH_KEY}}
jobs:
  instance:
    name: launching instance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: install-aws-cli
        uses: unfor19/install-aws-cli-action@master
      - run: aws --version
        shell: bash
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform Init
        id: init
        run: terraform init
      
      - name: Terraform Plan
        id: plan
        run: terraform plan
      
      - name: Terraform apply
        id: apply
        run: terraform apply --auto-approve
      - name: Deploy Docker Image to EC2
        uses: appleboy/ssh-action@master
        with:
         host: ${{ env.AWS_PUBLIC_SSH_KEY }}
         username: ec2-user
         key: ${{ env.AWS_PRIVATE_SSH_KEY }}
         run:
           sudo docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG   
    